# Generated by Django 3.0.6 on 2020-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200530_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='trial-product'),
            preserve_default=False,
        ),
    ]
